### ISSUE TITLE
UDP listener is deprecated

### ISSUE THREAD

**Issue by chhuang0123** [paksu/pytelegraf#2]
[On UDP listener page](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/udp_listener), it announced that UDP listener is deprecated. 

You could replace with socket_listener and update configuration sample...
Thank you so much...

PS> I am trying this great module for my custom metrics. :)

**Comment by paksu** [comment]
@chhuang0123 I'll look into this and update the example 👍

**Comment by paksu** [comment]
I looked into this. Looks like socket_listener input will arrive in Telegraf 1.3 which is not yet released. I will update the documentation when 1.3 is released. 

Until then you should be able to use UDP listener with the with Telegraf versions from 0.13 to 1.2.1. I just tested pytelegraf against the latest stable Telegraf and everything seemed to be working.

Also looks like UDP listener won't be immediately removed, only deprecated.

**Comment by chhuang0123** [comment]
Confirmed...
It still works on UDP listener...

**Comment by lucifercr07** [comment]
socket_listener input is now there with Telegraf v1.3 arrived, if you could please update the input example. 
However, [inputs.udp] still works fine, just with warning in telegraf logs.

**Comment by paksu** [comment]
Thank you all! I updated the example for Telegraf 1.3
